# Generated by Django 2.1.7 on 2019-02-19 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateTimeField(default=datetime.datetime(2019, 2, 19, 10, 46, 1, 187200, tzinfo=utc), verbose_name='data')),
                ('quantidade', models.IntegerField(default=1)),
                ('entrada', models.BooleanField(default=False)),
                ('saida', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bebida')),
            ],
        ),
    ]
