# Generated by Django 2.1.7 on 2019-02-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190219_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateTimeField()),
                ('quantidade', models.IntegerField(default=1)),
                ('entrada', models.BooleanField(default=False, null=True)),
                ('saida', models.BooleanField(default=False, null=True)),
                ('entousai', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bebida')),
            ],
        ),
        migrations.DeleteModel(
            name='EstoqueAdminForm',
        ),
        migrations.RemoveField(
            model_name='obs',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Obs',
        ),
    ]
