# Generated by Django 2.1.7 on 2019-02-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190219_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='Entrada ou Saida',
        ),
        migrations.AddField(
            model_name='estoque',
            name='entrada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='saida',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
